// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Body Header Message Module
 *
 * This module provides the body-header generation for safe-output workflows.
 * The body header is prepended to every message body generated by safe outputs
 * (issues, comments, pull requests, discussions).
 */

const { getMessages, renderTemplate, toSnakeCase } = require("./messages_core.cjs");

/**
 * @typedef {Object} BodyHeaderContext
 * @property {string} workflowName - Name of the workflow
 * @property {string} runUrl - URL of the workflow run
 */

/**
 * Get the body header text, using the custom template if configured.
 * Returns an empty string when no body-header is configured.
 * @param {BodyHeaderContext} ctx - Context for header generation
 * @returns {string} The rendered header text, or empty string if not configured
 */
function getBodyHeader(ctx) {
  const messages = getMessages();
  if (!messages?.bodyHeader) {
    return "";
  }

  const templateContext = toSnakeCase(ctx);
  return renderTemplate(messages.bodyHeader, templateContext);
}

module.exports = {
  getBodyHeader,
};
