// @ts-check
import { describe, it, expect, beforeEach, vi } from "vitest";

// messages_core.cjs calls core.warning on parse failures - provide a stub
const mockCore = {
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
};
global.core = mockCore;

const { getBodyHeader } = require("./messages_header.cjs");

const WORKFLOW = "My Workflow";
const RUN_URL = "https://github.com/owner/repo/actions/runs/99";

describe("messages_header", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    delete process.env.GH_AW_SAFE_OUTPUT_MESSAGES;
  });

  describe("getBodyHeader", () => {
    it("returns empty string when no body-header is configured", () => {
      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe("");
    });

    it("returns rendered template when body-header is configured", () => {
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
        bodyHeader: "> ⚠️ Generated by [{workflow_name}]({run_url}).",
      });

      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe(`> ⚠️ Generated by [${WORKFLOW}](${RUN_URL}).`);
    });

    it("supports snake_case placeholders", () => {
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
        bodyHeader: "> Generated by {workflow_name}.",
      });

      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe(`> Generated by ${WORKFLOW}.`);
    });

    it("supports camelCase placeholders", () => {
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
        bodyHeader: "> Run: {runUrl}",
      });

      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe(`> Run: ${RUN_URL}`);
    });

    it("returns empty string when messages env is set but body-header is absent", () => {
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
        footer: "> Custom footer",
      });

      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe("");
    });

    it("leaves unknown placeholders unchanged", () => {
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({
        bodyHeader: "> Header {workflow_name} {unknown_placeholder}",
      });

      const result = getBodyHeader({ workflowName: WORKFLOW, runUrl: RUN_URL });
      expect(result).toBe(`> Header ${WORKFLOW} {unknown_placeholder}`);
    });
  });
});
